### ISSUE TITLE
error in compiling the example 

### ISSUE THREAD

**Issue by liran827** [glenco/Example1#2]
Hi,
The example works well on my Macbook. However, when I tried to compile it on our server. I had the following problem. I can successfully build the glamer. Then I cd into the Example1 directory and generated Makefile with “cmake ." However, when I type make, it shows the following error message.

> cosma-b > make
> [100%] Building CXX object CMakeFiles/example.dir/example.cpp.o
> Linking CXX executable example
> /cosma/home/liran827/glamer/build/SLsimLib/libSLsimLib.a(internal_rayshooter_multi.cpp.o): In function 'Lens::rayshooterInternal(unsigned long, Point*)':
> 
> internal_rayshooter_multi.cpp:(.text+0x508): undefined reference to 'pthread_create'
> internal_rayshooter_multi.cpp:(.text+0x563): undefined reference to 'pthread_join'
> collect2: error ：ld return 1
> make[2]: **\* [example] error 1
> make[1]: **\* [CMakeFiles/example.dir/all] error 2
> make: **\* [all] error 2

I wonder if this means some flags are missing in the Makefile? 

Thank you!

Ran

**Comment by rbmetcalf** [comment]
Hmmm... Strange.  It seems to not recognise p_threads.
Can you tell us compiler and version you are using?
What do you think @ntessore?

**Comment by liran827** [comment]
I am using  g++ compiler of gnu_4.7.2 ;

**Comment by ntessore** [comment]
@rbmetcalf We fixed this recently, in a conversation from Feb 20th. Seems like it didn't end up in master.

**Comment by rbmetcalf** [comment]
@ntessore Can you merge it in then?

**Comment by ntessore** [comment]
I opened a PR in glenco/glamer, but it needs checking.
